export const modals = {
    LOGIN: 'SHOW_LOGIN',
    REGISTER: 'SHOW_REGISTER',
    CREATE_WALLET: 'SHOW_CREATE_WALLET',
    SAVE_WALLET: 'SHOW_SAVE_WALLET',
    CONFIRM_WALLET: 'SHOW_CONFIRM_WALLET',
    SEND_RECOVERY_EMAIL: 'SHOW_SEND_RECOVERY_EMAIL',
    ENTER_RECOVERY_TOKEN: 'SHOW_ENTER_RECOVERY_TOKEN',
    CHANGE_PASSWORD: 'SHOW_CHANGE_PASSWORD',
};

export const currency = {
    ROOMS_XML: 'EUR'
};

export const ROOMS_XML_CURRENCY = 'EUR';