let response = {
  'DefaultListing': {
    'type': '1',
    'country': '',
    'propertyType': '1',
    'roomType': 'entire',
    'dedicatedSpace': 'true',
    'size': '0',
    'guestsIncluded': 1,
    'bedroomsCount': 1,
    'bedrooms': [{ 'singleBedCount': 0, 'doubleBedCount': 0, 'kingBedCount': 0 }],
    'bathrooms': 1,
    'facilities': [],
    'street': '',
    'city': '',
    'name': '',
    'text': '',
    'interaction': '',
    'uploadedFiles': [],
    'uploadedFilesUrls': [],
    'uploadedFilesThumbUrls': [],
    'suitableForChildren': 'false',
    'suitableForInfants': 'false',
    'suitableForPets': 'false',
    'smokingAllowed': 'false',
    'eventsAllowed': 'false',
    'otherRuleText': '',
    'otherHouseRules': [],
    'checkinStart': '14:00',
    'checkinEnd': '20:00',
    'checkoutStart': '00:00',
    'checkoutEnd': '13:00',
    'defaultDailyPrice': '0',
    'cleaningFee': '0',
    'securityDeposit': '0',
    'currency': '2'
  }
};

export default (response.DefaultListing);